### ISSUE TITLE
Bad Characters

### ISSUE THREAD

**Issue by bjb28** [OrneLibrary/Carcosa#4]
Based on usage, it appears that `?` and `=` break the profile. When attempting to use this, the beacon continually reaches for the URI listed before the character.  

Example:
https://github.com/OrneLibrary/Carcosa/blob/d9bf8eb11a5210f28c7adc3a9d7f142e65b37c72/youtube.profile#L53

Reaches out for `/watch/`.

Suggest replacing the above characters at the following locations:

https://github.com/OrneLibrary/Carcosa/blob/d9bf8eb11a5210f28c7adc3a9d7f142e65b37c72/youtube.profile#L53
https://github.com/OrneLibrary/Carcosa/blob/d9bf8eb11a5210f28c7adc3a9d7f142e65b37c72/youtube.profile#L86

**Comment by Soul249** [comment]
Updated to reflect correct callouts

**Comment by ChickySticky** [comment]
Fixed in new Python Release
