### ISSUE TITLE
Update directions

### ISSUE THREAD

**Issue by bjb28** [OrneLibrary/Carcosa#5]
Directions to use Carcosa should look something like this:

  1. Move to `/home/cpt/cobaltstrike/certs` on the C2, put certs in there
  2. Run `carcosa.sh` 
          If it errors check the `privkey.pem` and `fullchain.pem` (if you remake the certs it adds a number)
  3. check `/home/cpt/cobalstrike/httpsProfile` and ensure the carcosa.store is there
  4. `cat youtube.profile` and at the bottom you should see the certs listed
  5. Start the teamserver

More detail will be needed but these steps here should allow for someone to use this with a bit more ease.

**Comment by ChickySticky** [comment]
Fixed in new Python Release
